### ISSUE TITLE
Best hyperparameters

### ISSUE THREAD

**Issue by mrsergazinov** [qile2000/LAMDA-TALENT#11]
Thank you so much for publishing this resource! It’s very helpful. 

If possible, could you, please, publish the best hyper-parameters for each method and dataset? This would be immensely useful for further extensions.

**Comment by mkmaa** [comment]
Thank you for acknowledging our work! We have organized and uploaded the best hyper-parameters for ~80% of the experiments, which can be found in the `example_datasets/best_hyperparameters.json` file. 

Since our experiments were run on multiple servers, it takes time to organize, and we will upload the remaining hyperparameters in the future.

**Comment by lixuechenAlfred** [comment]
@mkmaa Thank you for sharing the tuning results! I found that n_bins is tuned in modernNCA configs, however there is no data_num_enc in modernNCA's method, which is the sole function using n_bins.

**Comment by lixuechenAlfred** [comment]
> > @mkmaa Thank you for sharing the tuning results! I found that n_bins is tuned in modernNCA configs, however there is no data_num_enc in modernNCA's method, which is the sole function using n_bins.
> 
> Sorry for the confusion. This was due to the fact that in our exploration of numerical encoding, we added the `n_bins` hyper-parameter to all experiments for convenience. However, our final results are based on the default setting with no extra numerical encoding, so this hyper-parameter can be disregarded. We have updated the hyper-parameters.

Thanks for the quick reply!
